name: esp_provisioning
description: SpinDance Flutter federated plugin; wraps Espressif's native mobile provisioning libraries.
version: 1.0.4
publish_to: none

environment:
  sdk: "^3.6.1"

flutter:
  plugin:
    platforms:
      android:
        default_package: esp_provisioning_android
      ios:
        default_package: esp_provisioning_ios

dependencies:
  esp_provisioning_android:
    path: ../esp_provisioning_android
  esp_provisioning_ios:
    path: ../esp_provisioning_ios
  esp_provisioning_platform_interface:
    path: ../esp_provisioning_platform_interface
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1

dev_dependencies:
  build_runner: ^2.4.9
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0
  json_serializable: ^6.9.0
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^7.0.0
