name: esp_provisioning
description: SpinDance Flutter federated plugin; wraps Espressif's native mobile provisioning libraries.
version: 1.0.0
publish_to: none

environment:
  sdk: "^3.3.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: esp_provisioning_android
      ios:
        default_package: esp_provisioning_ios

dependencies:
  esp_provisioning_android:
    path: ../esp_provisioning_android
  esp_provisioning_ios:
    path: ../esp_provisioning_ios
  esp_provisioning_platform_interface:
    path: ../esp_provisioning_platform_interface
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: 4.8.1
  permission_handler: ^8.1.0

dev_dependencies:
  build_runner: ^2.4.9
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: 6.7.1
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
